# Generated by Django 4.2.5 on 2024-03-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_category_quizfolder_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionalternative',
            name='description',
            field=models.TextField(),
        ),
    ]
