name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: quizhero-app-env

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t quizhero-app --build-arg ALLOWED_HOSTS=${{ secrets.SSH_HOST }} .

    - name: Save Docker image
      run: |
        docker save quizhero-app > quizhero-app.tar

    - name: Upload Docker image to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "quizhero-app.tar"
        target: "~/quizhero"

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/quizhero
          docker load < quizhero-app.tar
          docker stop $(docker ps -q)
          docker rm $(docker ps -a -q)
          docker rmi $(docker images -q)
          docker run -d --name quizhero-app -p 8000:8000 quizhero-app
